# H2 Database connection settings (Exercise 1)
spring.datasource.url=jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=password
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

# Secondary DataSource configurations (Exercise 9)
spring.datasource.secondary.url=jdbc:h2:mem:secondarydb;DB_CLOSE_DELAY=-1
spring.datasource.secondary.driver-class-name=org.h2.Driver
spring.datasource.secondary.username=sa
spring.datasource.secondary.password=password

# H2 Console enablement
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# Show SQL & Logging
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Hibernate Batch Processing properties (Exercise 10)
spring.jpa.properties.hibernate.jdbc.batch_size=20
spring.jpa.properties.hibernate.order_inserts=true
spring.jpa.properties.hibernate.order_updates=true
